require_relative 'delivery/spy'
require_relative 'delivery/console_log'
require_relative 'delivery/smtp'
require_relative 'people/from_hash'
require_relative 'people/from_csv'
require_relative 'people/composite'
require_relative 'letters/template'